ucb:
  agent_kwargs:
    confidence: 1.0
  total_timesteps: 10_00
  eval_freq: 50
  buffer_size: 10_00

ppo:
  agent_kwargs:
    activation: tanh
  num_envs: 1
  num_steps: 100
  num_epochs: 5
  num_minibatches: 5
  learning_rate: 0.00075
  max_grad_norm: 0.5
  total_timesteps: 100_000
  eval_freq: 1000
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5

dqn:
  agent_kwargs:
    activation: swish
  num_envs: 1
  buffer_size: 50_000
  fill_buffer: 5_000
  batch_size: 100
  max_grad_norm: 10
  learning_rate: 0.001
  num_epochs: 5
  total_timesteps: 100_000
  eval_freq: 2_500
  # target_update_freq: 200
  polyak: 0.98
  eps_start: 1
  eps_end: 0.05
  exploration_fraction: 0.5
  gamma: 0.99
  ddqn: true
  normalize_observations: false