ppo:
  agent_kwargs:
    activation: tanh
  num_envs: 1
  num_steps: 100
  num_epochs: 5
  num_minibatches: 5
  learning_rate: 0.0003
  max_grad_norm: 0.5
  total_timesteps: 25_000
  eval_freq: 5000
  gamma: 0.95
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  buffer_size: 25_000
